// <auto-generated />
namespace MovieBackLogFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AutoIncrementBacklogid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AutoIncrementBacklogid));
        
        string IMigrationMetadata.Id
        {
            get { return "201908070020055_AutoIncrementBacklogid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
